inicio

    varinicio
        B inteiro;
        c lit;
        A real;
    varfim;

   escreva "Digite um numero:";
   leia B;

   {Este eh um comentario no meio do programa}

   B <- 2;
   B <- 3;

   

   {o contador B recebe valor dez e vai decaindo
   com as iteracoes}

   enquanto (B >= 0) faca
     escreva "iteracao...iterando...";
     B <- B -  1;
   fimenquanto

   escreva "programa finalizado";

fim
